### ISSUE TITLE
symbol lookup error: /usr/lib/jni/libnative-platform-curses.so: undefined symbol: tgetent on Ubuntu 17.10

### ISSUE THREAD

**Issue by Wruczek** [canonical-docs/snappy-docs#238]
After following [this](https://docs.snapcraft.io/build-snaps/java) tutorial on a fresh VM with Ubuntu 17.10 i got this after cloning the repo and running `snapcraft`. **Update:** It seems to work fine on 16.04.2
```
$ snapcraft
"grade" property not specified: defaulting to "stable"
Skipping pull desktop-glib-only (already ran)
Skipping build desktop-glib-only (already ran)
Skipping stage desktop-glib-only (already ran)
Skipping pull freeplane (already ran)
Preparing to build freeplane 
Building freeplane 
/usr/lib/jvm/java-8-openjdk-amd64/bin/java: symbol lookup error: /usr/lib/jni/libnative-platform-curses.so: undefined symbol: tgetent
Traceback (most recent call last):
  File "/snap/snapcraft/924/bin/snapcraft", line 11, in <module>
    load_entry_point('snapcraft==2.37', 'console_scripts', 'snapcraft')()
  File "/snap/snapcraft/924/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 565, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/snap/snapcraft/924/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "/snap/snapcraft/924/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/snap/snapcraft/924/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/snap/snapcraft/924/lib/python3.6/site-packages/snapcraft/cli/__main__.py", line 19, in <module>
    run(prog_name='snapcraft')
  File "/snap/snapcraft/924/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/snap/snapcraft/924/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/snap/snapcraft/924/lib/python3.6/site-packages/click/core.py", line 1043, in invoke
    return Command.invoke(self, ctx)
  File "/snap/snapcraft/924/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/snap/snapcraft/924/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/snap/snapcraft/924/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/snap/snapcraft/924/lib/python3.6/site-packages/snapcraft/cli/__init__.py", line 124, in run
    ctx.forward(lifecyclecli.commands['snap'])
  File "/snap/snapcraft/924/lib/python3.6/site-packages/click/core.py", line 553, in forward
    return self.invoke(cmd, **kwargs)
  File "/snap/snapcraft/924/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/snap/snapcraft/924/lib/python3.6/site-packages/snapcraft/cli/lifecycle.py", line 140, in snap
    project_options, directory=directory, output=output)
  File "/snap/snapcraft/924/lib/python3.6/site-packages/snapcraft/internal/lifecycle/_packer.py", line 45, in snap
    execute('prime', project_options)
  File "/snap/snapcraft/924/lib/python3.6/site-packages/snapcraft/internal/lifecycle/_runner.py", line 80, in execute
    _Executor(config, project_options).run(step, part_names)
  File "/snap/snapcraft/924/lib/python3.6/site-packages/snapcraft/internal/lifecycle/_runner.py", line 175, in run
    self._run_step(step, part, part_names)
  File "/snap/snapcraft/924/lib/python3.6/site-packages/snapcraft/internal/lifecycle/_runner.py", line 212, in _run_step
    getattr(part, step)()
  File "/snap/snapcraft/924/lib/python3.6/site-packages/snapcraft/internal/pluginhandler/__init__.py", line 325, in build
    script_runner.run(scriptlet=build_scriptlet)
  File "/snap/snapcraft/924/lib/python3.6/site-packages/snapcraft/internal/pluginhandler/_scriptlets.py", line 43, in run
    run([scriptlet_path], cwd=self._builddir)
  File "/snap/snapcraft/924/lib/python3.6/site-packages/snapcraft/internal/common.py", line 63, in run
    subprocess.check_call(['/bin/sh', f.name] + cmd, **kwargs)
  File "/snap/snapcraft/924/usr/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/bin/sh', '/tmp/tmpzhplc_55', '/tmp/tmp1vy7amjs']' returned non-zero exit status 127.
```

**Comment by Wruczek** [comment]
Ok, looks like Snapcraft and the tutorial i followed is only designed to work on Ubuntu 16.04 and 17.10 is not supported. Since the tutorial and Snapcraft worked very nicely on Ubuntu 16.04 i'm closing this issue.

**Comment by matthewpaulthomas** [comment]
I think this is still a valid bug. There’s nothing on that page which mentions that it requires Ubuntu 16.04 — or even that it requires Ubuntu at all. And while [the linked “Install snapd” page](https://docs.snapcraft.io/core/install) may single out 14.04 and 16.04, [the “Build snaps” page](https://docs.snapcraft.io/build-snaps/) claims that “`snapcraft` is … available on Ubuntu 16.04 LTS and above”.

So either the tutorial really is specific to Ubuntu 16.04, in which case it should say so; or this is a bug in snapcraft.

**Comment by Wruczek** [comment]
I've created this issue while trying out Snapcraft for Google Code-In. After mentioning this problem under my task I've got a reply: **We only aim for it to work on 16.04, so thanks for confirming it's got issues on 17.04!**. Looks like the docs should be updated.
