### ISSUE TITLE
Electron guide should suggest installing Docker (on Mac)

### ISSUE THREAD

**Issue by evandandrea** [canonical-docs/snappy-docs#272]
In order to build Electron apps for Linux but from a Mac, you need Docker for Mac installed. Otherwise:
```
☻  npm run dist

> @ dist /Users/ev/Branches/ramme
> yarn build && build -ml --ia32 --x64

yarn build v1.0.1
$ gulp build
[17:24:49] Failed to load external module @babel/register
[17:24:49] Requiring external module babel-register
[17:24:50] Using gulpfile ~/Branches/ramme/gulpfile.babel.js
[17:24:50] Starting 'build'...
[17:24:50] Starting 'clean'...
[17:24:50] Finished 'clean' after 16 ms
[17:24:50] Starting 'scripts'...
[17:24:50] Starting 'html'...
[17:24:50] Starting 'styles'...
[17:24:50] Starting 'assets'...
[17:24:50] gulp-image: Skipping unsupported image assets/icon.ico
[17:24:51] Finished 'html' after 388 ms
[17:24:51] Finished 'scripts' after 899 ms
[17:24:51] Finished 'styles' after 931 ms
[17:24:52] ✔ assets/icon-18x18.png -> before=14.9 KB after=770 B reduced=14.15 KB(95%)
[17:24:54] ✔ assets/icon.png -> before=49.55 KB after=18.72 KB reduced=30.84 KB(62.2%)
[17:24:54] Finished 'assets' after 3.91 s
[17:24:54] Finished 'build' after 3.93 s
✨  Done in 6.44s.
electron-builder 19.49.0
No native production dependencies
Packaging for darwin x64 using electron 1.7.10 to dist/mac
⚠️  App is not signed: cannot find valid "Developer ID Application" identity or custom non-Apple code signing certificate, see https://electron.build/code-signing

All identities:
  1) AC519C536CA640DF92EB519A76166551AF535A6E "com.apple.idms.appleid.prd.434f595654374a343030445075457648586e474172673d3d" (CSSMERR_TP_CERT_EXPIRED)
  2) 4E024EC2DB0B88CDE758B95F564A4859D4DA4B7B "com.apple.idms.appleid.prd.434f595654374a343030445075457648586e474172673d3d" (CSSMERR_TP_CERT_EXPIRED)
  3) 17011A0A17A42F1D246BCCE882E68D7CB9F3ED1E "com.apple.idms.appleid.prd.434f595654374a343030445075457648586e474172673d3d" (CSSMERR_TP_CERT_EXPIRED)
  4) 1EAF2DDF66E8B3A9187EC4380E66A06E597475BE "com.apple.idms.appleid.prd.434f595654374a343030445075457648586e474172673d3d"
     4 identities found

  Valid identities only
  1) 1EAF2DDF66E8B3A9187EC4380E66A06E597475BE "com.apple.idms.appleid.prd.434f595654374a343030445075457648586e474172673d3d"
     1 valid identities found
Building macOS zip
Building DMG
No native production dependencies
Packaging for linux x64 using electron 1.7.10 to dist/linux-unpacked
Downloading tmp-9122-0-electron-v1.7.10-linux-x64.zip
[============================================>] 100.0% of 51.22 MB (6.83 MB/s)
Building Snap for arch x64
Building tar.gz
Downloading tmp-9122-1-electron-v1.7.10-linux-ia32.zip
[>                                            ] 0.0% (0 B/s)
Downloading tmp-9122-1-electron-v1.7.10-linux-ia32.zip
[============================================>] 100.0% of 52.28 MB (6.54 MB/s)
Building Snap for arch ia32
Building tar.gz
Error: docker exited with code 125
    at ChildProcess.childProcess.once.code (/Users/ev/Branches/ramme/node_modules/builder-util/src/util.ts:220:14)
    at ChildProcess.g (events.js:292:16)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:920:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
From previous event:
    at spawn (/Users/ev/Branches/ramme/node_modules/builder-util/src/util.ts:183:3)
    at /Users/ev/Branches/ramme/node_modules/electron-builder-lib/src/targets/snap.ts:143:5
    at next (native)
From previous event:
    at SnapTarget.buildUsingDocker (/Users/ev/Branches/ramme/node_modules/electron-builder-lib/out/targets/snap.js:165:11)
    at /Users/ev/Branches/ramme/node_modules/electron-builder-lib/src/targets/snap.ts:106:18
    at next (native)
    at /Users/ev/Branches/ramme/node_modules/graceful-fs/graceful-fs.js:99:16
    at /Users/ev/Branches/ramme/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:123:15)
From previous event:
    at SnapTarget.build (/Users/ev/Branches/ramme/node_modules/electron-builder-lib/out/targets/snap.js:139:11)
    at taskManager.addTask.default.map.it (/Users/ev/Branches/ramme/node_modules/electron-builder-lib/src/platformPackager.ts:120:85)
From previous event:
    at LinuxPackager.packageInDistributableFormat (/Users/ev/Branches/ramme/node_modules/electron-builder-lib/src/platformPackager.ts:120:41)
    at /Users/ev/Branches/ramme/node_modules/electron-builder-lib/src/platformPackager.ts:116:10
From previous event:
    at LinuxPackager.pack (/Users/ev/Branches/ramme/node_modules/electron-builder-lib/out/platformPackager.js:195:11)
    at /Users/ev/Branches/ramme/node_modules/electron-builder-lib/src/packager.ts:345:24
From previous event:
    at Packager.doBuild (/Users/ev/Branches/ramme/node_modules/electron-builder-lib/out/packager.js:407:11)
    at /Users/ev/Branches/ramme/node_modules/electron-builder-lib/src/packager.ts:289:52
From previous event:
    at Packager._build (/Users/ev/Branches/ramme/node_modules/electron-builder-lib/out/packager.js:351:11)
    at /Users/ev/Branches/ramme/node_modules/electron-builder-lib/src/packager.ts:259:23
    at next (native)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at Packager.build (/Users/ev/Branches/ramme/node_modules/electron-builder-lib/out/packager.js:311:11)
    at /Users/ev/Branches/ramme/node_modules/electron-builder/src/builder.ts:287:40
    at next (native)
From previous event:
    at _build (/Users/ev/Branches/ramme/node_modules/electron-builder/out/builder.js:61:21)
    at build (/Users/ev/Branches/ramme/node_modules/electron-builder/src/builder.ts:257:10)
    at then (/Users/ev/Branches/ramme/node_modules/electron-builder/src/cli/cli.ts:49:4)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at Object.args [as handler] (/Users/ev/Branches/ramme/node_modules/electron-builder/src/cli/cli.ts:49:4)
    at Object.runCommand (/Users/ev/Branches/ramme/node_modules/yargs/lib/command.js:228:22)
    at Object.parseArgs [as _parseArgs] (/Users/ev/Branches/ramme/node_modules/yargs/yargs.js:1041:24)
    at Object.get [as argv] (/Users/ev/Branches/ramme/node_modules/yargs/yargs.js:957:21)
    at Object.<anonymous> (/Users/ev/Branches/ramme/node_modules/electron-builder/src/cli/cli.ts:43:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:502:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ dist: `yarn build && build -ml --ia32 --x64`
npm ERR! Exit status 1
```

**Comment by matthewpaulthomas** [comment]
Is the requirement for Docker on Mac specific to Electron apps? Or does this issue cite the Electron guide merely because that’s the only one allowing currently mentioning the possibility of building snaps on macOS?
