### ISSUE TITLE
Python steup returned error code 1 during snapcraft

### ISSUE THREAD

**Issue by Dominic1234** [canonical-docs/snappy-docs#286]
Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-AZlE7c-build/setup.py", line 26, in <module>
        import offlineimap
      File "offlineimap/__init__.py", line 20, in <module>
        from offlineimap.init import OfflineImap
      File "offlineimap/init.py", line 34, in <module>
        from offlineimap import threadutil, accounts, folder, mbnames
      File "offlineimap/accounts.py", line 23, in <module>
        import six
    ImportError: No module named six

Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-AZlE7c-build/

Traceback (most recent call last):
  File "/snap/snapcraft/1008/bin/snapcraft", line 11, in <module>
    load_entry_point('snapcraft==2.38', 'console_scripts', 'snapcraft')()
  File "/snap/snapcraft/1008/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 565, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/snap/snapcraft/1008/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "/snap/snapcraft/1008/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/snap/snapcraft/1008/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/snap/snapcraft/1008/lib/python3.6/site-packages/snapcraft/cli/__main__.py", line 19, in <module>
    run(prog_name='snapcraft')
  File "/snap/snapcraft/1008/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/snap/snapcraft/1008/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/snap/snapcraft/1008/lib/python3.6/site-packages/click/core.py", line 1043, in invoke
    return Command.invoke(self, ctx)
  File "/snap/snapcraft/1008/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/snap/snapcraft/1008/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/snap/snapcraft/1008/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/snap/snapcraft/1008/lib/python3.6/site-packages/snapcraft/cli/__init__.py", line 124, in run
    ctx.forward(lifecyclecli.commands['snap'])
  File "/snap/snapcraft/1008/lib/python3.6/site-packages/click/core.py", line 553, in forward
    return self.invoke(cmd, **kwargs)
  File "/snap/snapcraft/1008/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/snap/snapcraft/1008/lib/python3.6/site-packages/snapcraft/cli/lifecycle.py", line 139, in snap
    project_options, directory=directory, output=output)
  File "/snap/snapcraft/1008/lib/python3.6/site-packages/snapcraft/internal/lifecycle/_packer.py", line 45, in snap
    execute('prime', project_options)
  File "/snap/snapcraft/1008/lib/python3.6/site-packages/snapcraft/internal/lifecycle/_runner.py", line 79, in execute
    _Executor(config, project_options).run(step, part_names)
  File "/snap/snapcraft/1008/lib/python3.6/site-packages/snapcraft/internal/lifecycle/_runner.py", line 184, in run
    self._run_step(step, part, part_names)
  File "/snap/snapcraft/1008/lib/python3.6/site-packages/snapcraft/internal/lifecycle/_runner.py", line 221, in _run_step
    getattr(part, step)()
  File "/snap/snapcraft/1008/lib/python3.6/site-packages/snapcraft/internal/pluginhandler/__init__.py", line 279, in pull
    self.plugin.pull()
  File "/snap/snapcraft/1008/lib/python3.6/site-packages/snapcraft/plugins/python.py", line 190, in pull
    self._download_project()
  File "/snap/snapcraft/1008/lib/python3.6/site-packages/snapcraft/plugins/python.py", line 271, in _download_project
    process_dependency_links=self.options.process_dependency_links)
  File "/snap/snapcraft/1008/lib/python3.6/site-packages/snapcraft/plugins/_python/_pip.py", line 241, in download
    self._python_package_dir] + args, cwd=cwd)
  File "/snap/snapcraft/1008/lib/python3.6/site-packages/snapcraft/plugins/_python/_pip.py", line 433, in _run
    **kwargs)
  File "/snap/snapcraft/1008/lib/python3.6/site-packages/snapcraft/internal/common.py", line 64, in run
    subprocess.check_call(['/bin/sh', f.name] + cmd, **kwargs)
  File "/snap/snapcraft/1008/usr/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/bin/sh', '/tmp/tmp4a787bf7', '/home/dhruv/offlineimap/parts/offlineimap/install/usr/bin/python2', '-m', 'pip', 'download', '--disable-pip-version-check', '--dest', '/home/dhruv/offlineimap/parts/offlineimap/python-packages', '.']' returned non-zero exit status 1.

**Comment by Dominic1234** [comment]
Error during snapcraft

**Comment by daniellimws** [comment]
You might wanna use backticks to make the log more readable.

For example, 

\`\`\`
...
error message
...
\`\`\`

**Comment by Dominic1234** [comment]
Ok I have removed all unnecessary data

**Comment by daniellimws** [comment]
@Dominic1234 I meant adding 3 backticks to the start and end of your error log.

**Comment by Dominic1234** [comment]
Yes I did that too

**Comment by daniellimws** [comment]
@Dominic1234 weird over here it still looks the same

**Comment by Dominic1234** [comment]
Please check again.
