### ISSUE TITLE
Snap Creation Tutorial Issue

### ISSUE THREAD

**Issue by Dominic1234** [canonical-docs/snappy-docs#300]
On running snapcraft from this tutorial: 
https://docs.snapcraft.io/build-snaps/java
terminal provides this piece of output:

Staging desktop-glib-only 
Preparing to pull freeplane 
Hit https://repo.skype.com/deb stable InRelease                                  
Hit https://dl.winehq.org/wine-builds/ubuntu xenial InRelease                    
Ign http://dl.google.com/linux/chrome/deb stable InRelease                       
Hit http://dl.google.com/linux/chrome/deb stable Release                         
Get:1 http://security.ubuntu.com/ubuntu xenial-security InRelease [102 kB]       
Hit http://in.archive.ubuntu.com/ubuntu xenial InRelease                         
Hit http://repository.spotify.com stable InRelease                               
Ign http://download.opensuse.org/repositories/home:/stevenpusser/xUbuntu_16.10  InRelease
Hit http://ppa.launchpad.net/numix/ppa/ubuntu xenial InRelease                   
Get:2 http://in.archive.ubuntu.com/ubuntu xenial-updates InRelease [102 kB]      
Hit http://download.opensuse.org/repositories/home:/stevenpusser/xUbuntu_16.10  Release
Hit http://ppa.launchpad.net/noobslab/themes/ubuntu xenial InRelease             
Hit http://ppa.launchpad.net/js-reynaud/kicad-4/ubuntu xenial InRelease          
Get:3 http://in.archive.ubuntu.com/ubuntu xenial-backports InRelease [102 kB]    
Fetched 306 kB in 6s (0 B/s)                                                     
Err ca-certificates-java_20160321ubuntu1_all.deb                                 
  Could not connect to in.archive.ubuntu.com:80 (2001:67c:1360:8001::17). - connect (101: Network is unreachable) [IP: 2001:67c:1360:8001::17 80]
Fetched 0 B in 6s (0 B/s)                                                        
Traceback (most recent call last):
  File "/snap/snapcraft/1008/bin/snapcraft", line 11, in <module>
    load_entry_point('snapcraft==2.38', 'console_scripts', 'snapcraft')()
  File "/snap/snapcraft/1008/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 565, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/snap/snapcraft/1008/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "/snap/snapcraft/1008/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/snap/snapcraft/1008/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/snap/snapcraft/1008/lib/python3.6/site-packages/snapcraft/cli/__main__.py", line 19, in <module>
    run(prog_name='snapcraft')
  File "/snap/snapcraft/1008/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/snap/snapcraft/1008/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/snap/snapcraft/1008/lib/python3.6/site-packages/click/core.py", line 1043, in invoke
    return Command.invoke(self, ctx)
  File "/snap/snapcraft/1008/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/snap/snapcraft/1008/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/snap/snapcraft/1008/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/snap/snapcraft/1008/lib/python3.6/site-packages/snapcraft/cli/__init__.py", line 124, in run
    ctx.forward(lifecyclecli.commands['snap'])
  File "/snap/snapcraft/1008/lib/python3.6/site-packages/click/core.py", line 553, in forward
    return self.invoke(cmd, **kwargs)
  File "/snap/snapcraft/1008/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/snap/snapcraft/1008/lib/python3.6/site-packages/snapcraft/cli/lifecycle.py", line 139, in snap
    project_options, directory=directory, output=output)
  File "/snap/snapcraft/1008/lib/python3.6/site-packages/snapcraft/internal/lifecycle/_packer.py", line 45, in snap
    execute('prime', project_options)
  File "/snap/snapcraft/1008/lib/python3.6/site-packages/snapcraft/internal/lifecycle/_runner.py", line 79, in execute
    _Executor(config, project_options).run(step, part_names)
  File "/snap/snapcraft/1008/lib/python3.6/site-packages/snapcraft/internal/lifecycle/_runner.py", line 184, in run
    self._run_step(step, part, part_names)
  File "/snap/snapcraft/1008/lib/python3.6/site-packages/snapcraft/internal/lifecycle/_runner.py", line 214, in _run_step
    getattr(part, 'prepare_{}'.format(step))()
  File "/snap/snapcraft/1008/lib/python3.6/site-packages/snapcraft/internal/pluginhandler/__init__.py", line 271, in prepare_pull
    self._fetch_stage_packages()
  File "/snap/snapcraft/1008/lib/python3.6/site-packages/snapcraft/internal/pluginhandler/__init__.py", line 257, in _fetch_stage_packages
    stage_packages)
  File "/snap/snapcraft/1008/lib/python3.6/site-packages/snapcraft/internal/repo/_deb.py", line 308, in get
    return self._get(apt_cache)
  File "/snap/snapcraft/1008/lib/python3.6/site-packages/snapcraft/internal/repo/_deb.py", line 360, in _get
    self._cache.packages_dir, progress=self._apt.progress)
  File "/snap/snapcraft/1008/lib/python3.6/site-packages/apt/package.py", line 744, in fetch_binary
    (acqfile.destfile, acqfile.error_text))
apt.package.FetchError: The item '/home/dhruv/.cache/snapcraft/stage-packages/apt/fcb72a41330b200f31fe564285d5957ea9c8081118e9ebdad79d63fba2b16a9ded68a30c9f502d0280d4f1c8eb575a61/var/cache/apt/archives/ca-certificates-java_20160321ubuntu1_all.deb' could not be fetched: Could not connect to in.archive.ubuntu.com:80 (2001:67c:1360:8001::17). - connect (101: Network is unreachable) [IP: 2001:67c:1360:8001::17 80]

**Comment by popey** [comment]
Looks like you need to [disable IPv6](https://askubuntu.com/questions/440649/how-to-disable-ipv6-in-ubuntu-14-04) on your host. Try that and see?

**Comment by Dominic1234** [comment]
Ok Thanks
